networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.69.0.0/24

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.2
    ports:
      - 8123:8123    # qBittorrent Web UI
      - 6881:6881    # qBittorrent peer-to-peer traffic
      - 6789:6789    # NZBGet Web UI
      - 9696:9696    # Prowlarr Web UI
      - 3001:3001    # Firefox remote-access interface
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn    # Supported providers: ProtonVPN, Mullvad, etc.
      - VPN_TYPE=wireguard                # Choose 'wireguard' or 'openvpn'
      - HEALTH_VPN_DURATION_INITIAL=120s  # Delay before initial health check
      - WIREGUARD_PUBLIC_KEY=<PUBLIC_KEY>  # Replace with your WireGuard public key
      - WIREGUARD_PRIVATE_KEY=<PRIVATE_KEY> # Replace with your WireGuard private key
      - SERVER_COUNTRIES=<COUNTRY>         # Comma-separated list of server countries (e.g., Sweden)
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "www.mullvad.net"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true  # Trigger deunhealth to restart if unhealthy
    environment:
      - PUID=1000                            # Adjust to match host user ID
      - PGID=1000                            # Adjust to match host group ID
      - TZ=<YOUR_TIME_ZONE>		   # Set your local timezone (e.g., America/Los_Angeles)
      - WEBUI_PORT=8123                      # Internal web UI port
    volumes:
      - ./qbittorrent:/config                # Holds settings and torrent data
      - /mnt/nfs/jellyfin:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun           # Route all traffic through VPN container
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "www.mullvad.net"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"                     # Isolate from network, communicates via Docker socket
    environment:
      - LOG_LEVEL=info                      # 'debug' for verbose logs
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999 # Endpoint where deunhealth listens
      - TZ=<YOUR_TIME_ZONE>		     # Set your local timezone (e.g., America/Los_Angeles)
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		   # Set your local timezone (e.g., America/Los_Angeles)
      - NZBGET_USER=<USERNAME>             # Web UI login username
      - NZBGET_PASS=<PASSWORD>             # Web UI login password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nzbget:/config                    # NZBGet configuration and queue
      - /mnt/nfs/jellyfin:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		   # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		   # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config                   # Sonarr database and settings
      - /mnt/nfs/jellyfin:/data
    ports:
      - 8989:8989                         # Sonarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		   # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config                   # Radarr database and settings
      - /mnt/nfs/jellyfin:/data
    ports:
      - 7878:7878                         # Radarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.4

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		  # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config                  # Lidarr database and settings
      - /mnt/nfs/jellyfin:/data
    ports:
      - 8686:8686                         # Lidarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.5

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		  # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config                  # Bazarr settings and subtitle data
      - /mnt/nfs/jellyfin:/data
    ports:
      - 6767:6767                         # Bazarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.6

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    # Route browser traffic through the VPN for privacy
    network_mode: service:gluetun
    depends_on:
      - gluetun
    security_opt:
      - seccomp:unconfined                # Relax seccomp for certain plugins (optional)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIME_ZONE>		  # Set your local timezone (e.g., America/Los_Angeles)
    volumes:
      - ./firefox:/config                 # Firefox profile and settings
    shm_size: "1gb"                     # Allocate shared memory for performance
    restart: unless-stopped

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    # Optional Docker integration for service status cards
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata         # Homarr settings and widget data
    environment:
      - SECRET_ENCRYPTION_KEY=<KEY>       # Generate via 'openssl rand -hex 32'
    ports:
      - 7575:7575                         # Homarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.7
