services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080" # Or "8080:8080" if you prefer
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434' # Points to the ollama service below
      - 'WEBUI_SECRET_KEY=' # Optional: Change for production
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Or specify device IDs: ['0']
              capabilities: [gpu]
    restart: unless-stopped
    # Expose is not strictly needed for service-to-service comms in compose
    # expose:
    #   - 11434

volumes:
  open-webui:
  ollama:

