services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.domain.tld"
    volumes:
    # NFS Data directory mounted to /mnt/nfs/encrypted
      - /mnt/nfs/encrypted/vaultwarden:/data/
    ports:
    # Changed default ports to avoid conflict with Nextcloud
      - 8088:80