networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.69.0.0/24

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - /dev/net/tun:/dev/net/tun # If running on an LXC see readme for more info.
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.2
    ports:
      - 8123:8123 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
      # - 3001:3001 # firefox
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.mullvad.net || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true  # Trigger deunhealth to restart if unhealthy
    environment:
      - PUID=1010                            # Adjust to match host user ID
      - PGID=1010                            # Adjust to match host group ID
      - TZ=${TZ}
      - WEBUI_PORT=8123                      # Internal web UI port
    volumes:
      - ./qbittorrent:/config                # Holds settings and torrent data
      - /mnt/nfs/jellyfin:/data
      - /mnt/WD-ExtHDD/Jellyfin:/external
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun           # Route all traffic through VPN container
    healthcheck:
        test: ping -c 1 www.mullvad.net || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s

# See the 'qBittorrent Stalls with VPN Timeout' section for more information.
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"                     # Isolate from network, communicates via Docker socket
    environment:
      - LOG_LEVEL=info                      # 'debug' for verbose logs
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999 # Endpoint where deunhealth listens
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1010
      - PGID=1010
      - TZ=${TZ}
      - NZBGET_USER=<USERNAME>             # Web UI login username
      - NZBGET_PASS=<PASSWORD>             # Web UI login password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nzbget:/config                    # NZBGet configuration and queue
      - /mnt/nfs/jellyfin:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config                   # Sonarr database and settings
      - /mnt/truenas_data/jellyfin_data:/data
      - /mnt/truenas_data/jellyfin_data/tv:/tv
    ports:
      - 8989:8989                         # Sonarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config                   # Radarr database and settings
      - /mnt/truenas_data/jellyfin_data:/data
      - /mnt/truenas_data/jellyfin_data/movies:/movies
    ports:
      - 7878:7878                         # Radarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.4

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config                  # Bazarr settings and subtitle data
      - /mnt/truenas_data/jellyfin_data:/data
    ports:
      - 6767:6767                         # Bazarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.6

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata         # Homarr settings and widget data
    environment:
      - SECRET_ENCRYPTION_KEY=<KEY>       # Generate via 'openssl rand -hex 32'
    ports:
      - 7575:7575                         # Homarr Web UI
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.7

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /srv/appdata/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.8
    restart: unless-stopped

  # lidarr:
    # container_name: lidarr
    # image: lscr.io/linuxserver/lidarr:latest
    # restart: unless-stopped
    # volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - ./lidarr:/config
      # - /mnt/nfs/jellyfin:/data
    # environment:
     # - PUID=1000
     # - PGID=1000
     # - TZ=${TZ}
    # ports:
      # - 8686:8686
    # networks:
      # servarrnetwork:
        # ipv4_address: 172.69.0.5

  # readarr:
    # image: lscr.io/linuxserver/readarr:develop
    # container_name: readarr
    # restart: unless-stopped
    # environment:
      # - PUID=1000
      # - PGID=1000
      # - TZ=${TZ}
    # volumes:
      # - ./readarr:/config
      # - /mnt/WD-ExtHDD/Jellyfin:/data
      # - /mnt/truenas_data/jellyfin_data:/data
    # ports:
      # - 8787:8787
    # networks:
      # servarrnetwork:
        # ipv4_address: 172.69.0.5

  # firefox:
    # image: lscr.io/linuxserver/firefox:latest
    # container_name: firefox
    # network_mode: "service:gluetun"
    # depends_on:
      # - gluetun
    # security_opt:
      # - seccomp:unconfined #optional
    # environment:
      # - PUID=1000
      # - PGID=1000
      # - TZ=${TZ}
    # volumes:
      # - ./firefox:/config
    # shm_size: "1gb"
    # restart: unless-stopped