volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    container_name: nextcloud-db
    networks:
      - nextcloud-net
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nfs/apps/nextcloud:/var/www/html/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQ_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - traefik-proxy
      - nextcloud-net
    labels:
      - traefik.enable=true

      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=cloudflare

      - traefik.http.routers.nextcloud-lan.rule=Host(`nextcloud.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.nextcloud-lan.entrypoints=websecure
      - traefik.http.routers.nextcloud-lan.tls=true
      - traefik.http.routers.nextcloud-lan.tls.certresolver=cloudflare

      - traefik.http.services.nextcloud.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
  nextcloud-net:
     external: false
