volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<YOUR_MYSQL_ROOT_PASSWORD>
      - MYSQL_PASSWORD=<YOUR_MYSQL_USER_PASSWORD>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      # Data directory mounted to /mnt/nfs/family/nextcloud
      - /mnt/nfs/family/nextcloud:/var/www/html/data
    environment:
      - PUID=1005
      - PGID=1005
      - MYSQL_PASSWORD=<YOUR_MYSQL_USER_PASSWORD>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
