services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<YOUR_TIMEZONE>
    volumes:
      - <CHOOSE_PATH_FOR_HOMEASSISTANT_DATA>/homeassistant/data:/config
    ports:
      - 8123:8123
    # devices:
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped