http:
  routers:
    qbittorrent:
      rule: "Host(`qb.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: qbittorrent-gluetun
    prowlarr:
      rule: "Host(`prowlarr.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: prowlarr-gluetun
    jellyfin:
      rule: "Host(`jellyfin.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: jellyfin-ubuntu
    homeassistant:
      rule: "Host(`homeassistant.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: homeassistant-ubuntu
    neko:
      rule: "Host(`neko.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: neko-ubuntu

  services:
    qbittorrent-gluetun:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8122"
    prowlarr-gluetun:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:9696"
    jellyfin-ubuntu:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8096"
    homeassistant-ubuntu:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8123"
    neko-ubuntu:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8880"
