http:
  routers:
    qbittorrent:
      rule: "Host(`qb.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: qbittorrent-gluetun
    prowlarr:
      rule: "Host(`prowlarr.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: prowlarr-gluetun
    jellyfin:
      rule: "Host(`jellyfin.domain.tld`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: jellyfin-ubuntu

  services:
    qbittorrent-gluetun:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8122"
    prowlarr-gluetun:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:9696"
    jellyfin-ubuntu:
      loadBalancer:
        servers:
          - url: "http://172.23.51.30:8096"
