services:
  taskwise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://YOUR_SERVER_IP:3100
    ports:
      - "3000:3000"  # Web UI
      - "3100:3100"  # Database API
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Persists your database
      - ./logs:/app/logs  # Stores logs outside the container