services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    env_file: .env
    ports:
      - 8881:80
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true

      - traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAIN}`)
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.routers.it-tools.tls.certresolver=cloudflare

      - traefik.http.routers.it-tools-lan.rule=Host(`it-tools.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.it-tools-lan.entrypoints=websecure
      - traefik.http.routers.it-tools-lan.tls=true
      - traefik.http.routers.it-tools-lan.tls.certresolver=cloudflare

      - traefik.http.services.it-tools.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
