services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    networks:
      - traefik-proxy
      - tmdb-net
    ports:
      - "8808:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=${WEB_SEARCH_ENGINE}
      - SEARXNG_QUERY_URL=${SEARXNG_QUERY_URL}
      - WEB_SEARCH_RESULT_COUNT=${WEB_SEARCH_RESULT_COUNT}
    volumes:
      - open-webui:/app/backend/data
    labels:
      - traefik.enable=true

      - traefik.http.routers.open-webui.rule=Host(`open-webui.${DOMAIN}`)
      - traefik.http.routers.open-webui.entrypoints=websecure
      - traefik.http.routers.open-webui.tls=true
      - traefik.http.routers.open-webui.tls.certresolver=cloudflare

      - traefik.http.routers.open-webui-lan.rule=Host(`open-webui.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.open-webui-lan.entrypoints=websecure
      - traefik.http.routers.open-webui-lan.tls=true
      - traefik.http.routers.open-webui-lan.tls.certresolver=cloudflare

      - traefik.http.services.open-webui.loadbalancer.server.port=8080

volumes:
  open-webui:

networks:
  traefik-proxy:
    external: true
  tmdb-net:
    external: true
