services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=<YOUR_TIMEZONE>
    ports:
      - 5055:5055
    volumes:
      - /srv/appdata/jellyseerr:/app/config
    restart: unless-stopped
